$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline
display_name: Cough Classification Pipeline
experiment_name: classification

inputs:
  data_dir:
    type: uri_folder
    path: azureml:sounds-dataset:1

outputs:
  model:
    mode: upload
  registration_details:
    mode: upload

settings:
  default_compute: azureml:cpu-brent-auto #maak hier later een default van

jobs:
  training:
    type: command
    component: ./components/training/training.yaml
    inputs:
      data_dir: ${{parent.inputs.data_dir}}
    outputs:
      output_folder: ${{parent.outputs.model}}

  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.21
    inputs:
      model_name: cough-classification
      model_type: custom_model
      model_path: ${{parent.jobs.training.outputs.output_folder}}
    outputs:
      registration_details_folder: ${{parent.outputs.registration_details}}