name: project-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - setuptools=68.2.2
  - pip
  - pip:
      - tensorflow==2.13.0
      - tensorflow-hub==0.16.1
      - protobuf<5
      - librosa
      - soundfile
      - scipy
      - matplotlib
      - scikit-learn
      - pandas
      - joblib
      - azure-ai-ml
      - mlflow
      - azureml-mlflow