$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json

name: training_project
display_name: Training an AI model
description: Trains an AI model by inputting a lot of training and testing data.
version: 4

type: command

inputs:
  split_data:
    type: uri_folder

outputs:
  output_folder:
    type: uri_folder
    mode: rw_mount

code: ./code

environment: azureml:project-env:13

command: python training.py --split_data ${{inputs.split_data}} --output_folder ${{outputs.output_folder}}