name: Redeploy Model

on:
  workflow_run:
    workflows: ["Retrain Model"]
    types:
      - completed

jobs:
  redeploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Azure ML defaults
        run: |
          az configure --defaults group=azure-ai workspace=brent-develter-ml location=francecentral

      - name: Download latest LSTM model
        run: |
          az ml model download --name cough-classification-lstm --version $(az ml model list --name cough-classification-lstm --query "max_by([].version, &to_number(@))" -o tsv) --download-path ./inference/models
          
      - name: Download latest 1D CNN model
        run: |
          az ml model download --name cough-classification-cnn --version $(az ml model list --name cough-classification-cnn --query "max_by([].version, &to_number(@))" -o tsv) --download-path ./inference/models

      - name: Push new model to github
        run: |
          git add .
          git commit -m "automatic model update"
          git push