name: Redeploy Model

on:
  workflow_run:
    workflows: ["Retrain Model"]
    types:
      - completed

jobs:
  redeploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Azure ML defaults
        run: |
          az configure --defaults group=azure-ai workspace=brent-develter-ml location=francecentral

      - name: Download latest model
        run: |
          az ml model download --name animal-classification --version $(az ml model list --name animal-classification --query "[0].version" -o tsv) --download-path ./inference/models

      - name: Restart API container with new model
        run: |
          cd inference
          docker compose down
          docker compose up --build -d